name: CD

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: true

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Update Git submodules
        run: git submodule update --remote --recursive

      - name: Build and test with Gradle
        run: ./gradlew test

      - name: Build and push Docker image
        run: ./gradlew clean bootBuildImage -PDOCKERHUB_ID=${{ secrets.DOCKERHUB_ID }} -PDOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}

      - name: SSH into NCP instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_SSH_PORT }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_URL }}
            docker ps -f name=be-server -q | xargs --no-run-if-empty docker container stop
            docker ps -a -f name=be-server -q | xargs --no-run-if-empty docker container rm
            docker run -d --name be-server ${{ secrets.DOCKERHUB_URL }}
